# Generated by Django 2.2.14 on 2020-12-04 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('publicacion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 12, 3, 23, 25, 54, 780108), null=True)),
                ('comentarios', models.ManyToManyField(related_name='coment', to='comentarios.Comentario')),
                ('tag', models.ManyToManyField(related_name='tag', to='tags.Tag')),
            ],
        ),
    ]
